### ISSUE TITLE
UPDI via UART?

### ISSUE THREAD

**Issue by WizardUli** [mraardvark/pyavrdebug#2]
Would it be possible to support debugging via UART? Seems like `UpdiApplication` is missing required functionality?

**Comment by mraardvark** [comment]
@WizardUli while this is a nice thought, unfortunately the debug protocol for AVR is not public information... :/

**Comment by WizardUli** [comment]
Grrr... Time to reverse engineer it. Which debug adapter is the cheapest? :D
Anyway, I think I can close this issue.
